- name: 'Enzo Bassano'
  pic: 'EBassano.JPG'

- name: 'Luis Cárcamo'

- name: 'Andrés Cerda'
  pic: 'ACerda.JPG'

- name: 'Tomás De la Sotta'
  pic: 'TDLSotta.JPG'

- name: 'Santiago Ernst'
  pic: 'SErnst.JPG'

- name: 'Benjamín Hunfan'
  pic: 'BHunfan.JPG'

- name: 'Miguel Jaramillo'
  pic: 'MJaramillo'

- name: 'Eduardo Jorquera'
  pic: 'EJorquera'

- name: 'Eduardo Loayza'
  pic: 'ELoayza.JPG'

- name: 'Pedro Martínez'
  pic: 'PMartinez.JPG'

- name: 'Camilo Meneses'
  pic: 'CMeneses.JPG'

- name: 'Raimundo Olckers'

- name: 'Dario Osses'
  pic: 'DOsses.JPG'

- name: 'Luis Plaza'

- name: 'Ignacio Poblete'
  pic: 'IPoblete.JPG'

- name: 'Ariel Riveros'

- name: 'Emilio Roa'
  pic: 'ERoa.JPG'

- name: 'Diego Rubio'
  pic: 'DRubio.JPG'

- name: 'Maximiliano Varas'
  pic: 'MVaras.JPG'

- name: 'Sebastián Zapata'
  pic: 'SZapata.JPG'
